#pragma once

// World
#define MAX_HEIGHT 128
#define MAX_INSTANCE_OFFSETS 20480
#define RENDERER_THREAD_COUNT 2
#define CHUNK_LOADER_THREAD_COUNT 3
#define PRELOAD_DISTANCE 3

// Sound Engine
#define SAME_SOUND_COUNT 9
