#pragma once

// World
#define MAX_HEIGHT 128
#define MAX_INSTANCE_OFFSETS 10240
#define RENDERER_THREAD_COUNT 4
#define CHUNK_LOADER_THREAD_COUNT 3
#define EXTRA_RENDER_DISTANCE 2

// Sound Engine
#define SAME_SOUND_COUNT 9
