name: Create Release
on:
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      
      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

      - name: Set build number
        env:
          REF: ${{ github.ref }}
        run: |
          $Build = Get-Date -Format "yyMMdd"
          echo "RELEASE_VERSION=$Build" >> $env:GITHUB_ENV

      - name: Set Username and Email
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          
      - name: Rename ZIP
        run: |
          $Build = Get-Date -Format "yyMMdd"
          Move-Item -Path ".\build\Game.zip" -Destination "Game Build $Build.zip"

      - name: release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ env.RELEASE_VERSION }}"
          title: "Build ${{ env.RELEASE_VERSION }}"
          prerelease: false
          files: |
            Game Build ${{ env.RELEASE_VERSION }}.zip