name: create-release
on:
  workflow_dispatch:

env:
  SOLUTION_FILE_PATH: .
  BUILD_CONFIGURATION: Release

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      
      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

      - name: Set build number
        env:
          REF: ${{ github.ref }}
        run: |
          for /f %a in ('powershell -command "[DateTime]::Now.ToString(\"yyMMdd\")"') do set build=%a
          echo "RELEASE_VERSION=%build%" >> $GITHUB_ENV

      - name: Set Username and Email
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          
      - name: Create ZIP
        run: |
          New-Item -Path . -Name "Game" -ItemType "directory"
          Copy-Item .\assets\ .\Game\ -Recurse
          Copy-Item ".\build\Release\Minecraft Clone.exe" .\Game\
          Compress-Archive -Path Game -DestinationPath Game.zip
        shell: pwsh

      - name: release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "v${{ env.BUILD }}"
          prerelease: false
          files: |
            Game.zip